name: mldd23
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - anyio=3.6.2
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.2
  - biopython=1.81
  - black=23.1.0
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=6.0.0
  - bokeh=3.0.3
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - cattrs=22.2.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - cftime=1.6.2
  - charset-normalizer=2.1.1
  - chembl_webresource_client=0.10.8
  - click=8.1.3
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.7
  - cryptography=39.0.1
  - cuda=11.7.1
  - cuda-cccl=11.7.91
  - cuda-command-line-tools=11.7.1
  - cuda-compiler=11.7.1
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cuobjdump=11.7.91
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.7.91
  - cuda-demo-suite=12.0.140
  - cuda-documentation=12.0.140
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-memcheck=11.8.86
  - cuda-nsight-compute=12.0.1
  - cuda-nvcc=11.7.99
  - cuda-nvdisasm=12.0.140
  - cuda-nvml-dev=11.7.91
  - cuda-nvprof=12.0.146
  - cuda-nvprune=11.7.91
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-nvvp=12.0.146
  - cuda-runtime=11.7.1
  - cuda-sanitizer-api=12.0.140
  - cuda-toolkit=11.7.1
  - cuda-tools=11.7.1
  - cuda-visual-tools=11.7.1
  - cudatoolkit=11.6.0
  - curl=7.88.1
  - cycler=0.11.0
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - easydict=1.9
  - entrypoints=0.4
  - exceptiongroup=1.1.0
  - executing=1.2.0
  - expat=2.5.0
  - fasteners=0.17.3
  - flit-core=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - fuzzywuzzy=0.18.0
  - gettext=0.21.1
  - gevent=22.10.2
  - glew=2.1.0
  - glib=2.74.1
  - glib-tools=2.74.1
  - glm=0.9.9.4
  - greenlet=2.0.2
  - grequests=0.6.0
  - griddataformats=1.0.1
  - gsd=2.8.0
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - h5py=3.8.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.12.0
  - iniconfig=2.0.0
  - intel-openmp=2023.0.0
  - ipykernel=6.21.2
  - ipython=8.10.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - isort=5.12.0
  - itsdangerous=2.1.2
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.0.3
  - jupyter_console=6.6.2
  - jupyter_core=5.2.0
  - jupyter_events=0.6.3
  - jupyter_server=2.3.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.14
  - lerc=4.0.0
  - levenshtein=0.20.9
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.3.66
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.124
  - libcurand=10.3.1.124
  - libcurand-dev=10.3.1.124
  - libcurl=7.88.1
  - libcusolver=11.4.0.1
  - libcusolver-dev=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.2
  - libglib=2.74.1
  - libhwloc=2.9.0
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnetcdf=4.9.1
  - libnpp=11.7.4.75
  - libnpp-dev=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.8.0.2
  - libogg=1.3.4
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.2
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - matplotlib-inline=0.1.6
  - mdanalysis=2.4.2
  - mistune=2.0.5
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mmtf-python=1.1.3
  - mrcfile=1.4.3
  - msgpack-python=1.0.4
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - nbclassic=0.5.2
  - nbclient=0.7.2
  - nbconvert=7.2.9
  - nbconvert-core=7.2.9
  - nbconvert-pandoc=7.2.9
  - nbformat=5.7.3
  - nest-asyncio=1.5.6
  - netcdf4=1.6.2
  - networkx=3.0
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nsight-compute=2022.4.1.6
  - numpy=1.24.2
  - openbabel=3.1.1
  - openjpeg=2.5.0
  - openssl=3.0.8
  - packaging=23.0
  - pandas=1.5.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.11.0
  - patsy=0.5.3
  - pbr=5.11.1
  - pcre2=10.40
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.0.0
  - pluggy=1.0.0
  - ply=3.11
  - pmw=2.0.1
  - pooch=1.6.0
  - prolif=1.1.0
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.4
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - py3dmol=2.0.1.post1
  - pycairo=1.23.0
  - pycparser=2.21
  - pyedr=0.7.1
  - pyg=2.1.0
  - pygments=2.14.0
  - pymol-open-source=2.5.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pypdb=2.2
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - pytdc=0.3.8
  - pytest=7.2.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-json-logger=2.0.7
  - python-levenshtein=0.20.9
  - python_abi=3.9
  - pytng=0.3.0
  - pytorch=1.12.1
  - pytorch-cluster=1.6.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytorch-scatter=2.0.9
  - pytorch-sparse=0.6.15
  - pytz=2022.7.1
  - pywin32=228
  - pywinpty=2.0.10
  - pyyaml=6.0
  - pyzmq=25.0.0
  - qt-main=5.15.8
  - qtconsole=5.4.0
  - qtconsole-base=5.4.0
  - qtpy=2.3.0
  - qvina=2.1.0
  - rapidfuzz=2.13.7
  - rdkit=2022.09.1
  - reportlab=3.6.12
  - requests=2.28.2
  - requests-cache=0.9.8
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scikit-learn=1.2.1
  - scipy=1.10.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.0
  - setuptools=67.4.0
  - sip=6.7.7
  - six=1.16.0
  - smina=2020.12.10
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlalchemy=2.0.4
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - tbb=2021.8.0
  - terminado=0.17.0
  - threadpoolctl=3.1.0
  - tidynamics=1.0.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - ucrt=10.0.22621.0
  - ujson=5.7.0
  - unicodedata2=15.0.0
  - url-normalize=1.4.3
  - urllib3=1.26.14
  - vc=14.3
  - vs2015_runtime=14.34.31931
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.2.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zope.event=4.6
  - zope.interface=5.5.2
  - zstd=1.5.2
prefix: C:\Users\tomas\.conda\envs\mldd23
